name: Upload to S3

on:
  push:
    branches:
      - main
    paths:
      - movielist.json

jobs:
  minify-and-upload-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Check Out Code
        uses: actions/checkout@v3
      - name: Minify json
        run: jq --compact-output '.lists |= map(select(.hidden != true))' movielist.json > movielist.min.json
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        run: aws s3 cp movielist.min.json s3://${AWS_BUCKET}/movielist.json
