name: Upload to S3

on:
  push:
    branches:
      - main

    paths:
      - movielist.json
      - .github/workflows/workflow.yml

permissions:
  contents: read

jobs:
  minify-and-upload-to-s3:

    permissions:
      id-token: write
      contents: read

    uses: jluszcz/github-utils/.github/workflows/minify-and-upload.yml@v1

    with:
      aws-region: us-east-2
      project: movielist
      s3-key-prefix: moviel.ist
      bucket-prefix: list-of-lists

    secrets:
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
